const environments = {
  AWS_IDENTITY_POOL_ID: process.env.REACT_APP_AWS_IDENTITY_POOL_ID,
  AWS_REGION: process.env.REACT_APP_AWS_REGION,
  AWS_USER_POOL_ID: process.env.REACT_APP_AWS_USER_POOL_ID,
  AWS_USER_POOL_WEB_CLIENT_ID: process.env.REACT_APP_AWS_USER_POOL_WEB_CLIENT_ID,
  AWS_OAUTH_DOMAIN: process.env.REACT_APP_AWS_OAUTH_DOMAIN,
  AUTH0_DOMAIN: process.env.REACT_APP_AUTH0_DOMAIN,
  AUTH0_CLIENT_ID: process.env.REACT_APP_AUTH0_CLIENT_ID,
  AUTH0_AUDIENCE: process.env.REACT_APP_AUTH0_AUDIENCE,
  GOOGLE_CLIENT_ID: process.env.REACT_APP_GOOGLE_CLIENT_ID,
};

export default { ...environments };
